//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candy
    {
        public int ID { get; set; }
        public string Type_of_Candy { get; set; }
        public string Color_of_Candy { get; set; }
        public Nullable<int> Number_of_Candies { get; set; }
    }
}
